CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260203034011_InitialCreate') THEN
    CREATE TABLE "ComfortMessages" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "SenderId" uuid NOT NULL,
        "ReceiverId" uuid NOT NULL,
        "TargetLogId" bigint,
        "Content" character varying(500) NOT NULL,
        "Status" integer NOT NULL,
        "IsThanked" boolean NOT NULL,
        "SentAt" timestamp with time zone NOT NULL,
        "ThankedAt" timestamp with time zone,
        CONSTRAINT "PK_ComfortMessages" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260203034011_InitialCreate') THEN
    CREATE TABLE "Users" (
        "UserId" uuid NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "LastActiveAt" timestamp with time zone NOT NULL,
        "IsBanned" boolean NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("UserId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260203034011_InitialCreate') THEN
    CREATE TABLE "EmotionLogs" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid NOT NULL,
        "Emotion" integer NOT NULL,
        "Intensity" integer NOT NULL,
        "Region" character varying(50) NOT NULL,
        "Tags" character varying(200) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_EmotionLogs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_EmotionLogs_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260203034011_InitialCreate') THEN
    CREATE INDEX "IX_EmotionLogs_CreatedAt" ON "EmotionLogs" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260203034011_InitialCreate') THEN
    CREATE INDEX "IX_EmotionLogs_Region_CreatedAt" ON "EmotionLogs" ("Region", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260203034011_InitialCreate') THEN
    CREATE INDEX "IX_EmotionLogs_UserId" ON "EmotionLogs" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260203034011_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260203034011_InitialCreate', '10.0.2');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260204125853_AddIsAdminToUser') THEN
    ALTER TABLE "Users" ADD "IsAdmin" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260204125853_AddIsAdminToUser') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260204125853_AddIsAdminToUser', '10.0.2');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260204130433_AddAdminAndNewEmotions') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260204130433_AddAdminAndNewEmotions', '10.0.2');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260204130649_UpdateUserAndEmotions') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260204130649_UpdateUserAndEmotions', '10.0.2');
    END IF;
END $EF$;
COMMIT;

