export const DISTRICT_TRANSLATION: Record<string, string> = {
    // Seoul
    'Jongno-gu': '종로구',
    'Yongsan-gu': '용산구',
    'Seongdong-gu': '성동구',
    'Gwangjin-gu': '광진구',
    'Dongdaemun-gu': '동대문구',
    'Jungnang-gu': '중랑구',
    'Seongbuk-gu': '성북구',
    'Gangbuk-gu': '강북구',
    'Dobong-gu': '도봉구',
    'Nowon-gu': '노원구',
    'Eunpyeong-gu': '은평구',
    'Seodaemun-gu': '서대문구',
    'Mapo-gu': '마포구',
    'Yangcheon-gu': '양천구',
    'Guro-gu': '구로구',
    'Geumcheon-gu': '금천구',
    'Yeongdeungpo-gu': '영등포구',
    'Dongjak-gu': '동작구',
    'Gwanak-gu': '관악구',
    'Seocho-gu': '서초구',
    'Gangnam-gu': '강남구',
    'Songpa-gu': '송파구',
    'Gangdong-gu': '강동구',

    // Common Names (Duplicates removed)
    'Jung-gu': '중구',
    'Dong-gu': '동구',
    'Seo-gu': '서구',
    'Nam-gu': '남구',
    'Buk-gu': '북구',
    'Gangseo-gu': '강서구',

    // Busan (Specific)
    'Sasang-gu': '사상구',
    'Saha-gu': '사하구',
    'Yeonje-gu': '연제구',
    'Suyeong-gu': '수영구',
    'Haeundae-gu': '해운대구',
    'Geumjeong-gu': '금정구',
    'Dongnae-gu': '동래구',
    'Busanjin-gu': '부산진구',
    'Yeongdo-gu': '영도구',
    'Gijang-gun': '기장군',

    // Daegu (Specific)
    'Dalseong-gun': '달성군',
    'Dalseo-gu': '달서구',
    'Suseong-gu': '수성구',

    // Incheon (Specific)
    'Ganghwa-gun': '강화군',
    'Ongjin-gun': '옹진군',
    'Gyeyang-gu': '계양구',
    'Bupyeong-gu': '부평구',
    'Namdong-gu': '남동구',
    'Yeonsu-gu': '연수구',
    'Michuhol-gu': '미추홀구',

    // Gyeonggi-do (Major Cities)
    'Suwon-si': '수원시',
    'Seongnam-si': '성남시',
    'Uijeongbu-si': '의정부시',
    'Anyang-si': '안양시',
    'Bucheon-si': '부천시',
    'Gwangmyeong-si': '광명시',
    'Pyeongtaek-si': '평택시',
    'Dongducheon-si': '동두천시',
    'Ansan-si': '안산시',
    'Goyang-si': '고양시',
    'Gwacheon-si': '과천시',
    'Guri-si': '구리시',
    'Namyangju-si': '남양주시',
    'Osan-si': '오산시',
    'Siheung-si': '시흥시',
    'Gunpo-si': '군포시',
    'Uiwang-si': '의왕시',
    'Hanam-si': '하남시',
    'Yongin-si': '용인시',
    'Paju-si': '파주시',
    'Icheon-si': '이천시',
    'Anseong-si': '안성시',
    'Gimpo-si': '김포시',
    'Hwaseong-si': '화성시',
    'Gwangju-si': '광주시',
    'Yangju-si': '양주시',
    'Pocheon-si': '포천시',
    'Yeoju-si': '여주시',
    'Yeoncheon-gun': '연천군',
    'Gapyeong-gun': '가평군',
    'Yangpyeong-gun': '양평군',

    // Gangwon-do
    'Chuncheon-si': '춘천시',
    'Wonju-si': '원주시',
    'Gangneung-si': '강릉시',
    'Donghae-si': '동해시',
    'Taebaek-si': '태백시',
    'Sokcho-si': '속초시',
    'Samcheok-si': '삼척시',
    'Hongcheon-gun': '홍천군',
    'Hoengseong-gun': '횡성군',
    'Yeongwol-gun': '영월군',
    'Pyeongchang-gun': '평창군',
    'Jeongseon-gun': '정선군',
    'Cheorwon-gun': '철원군',
    'Hwacheon-gun': '화천군',
    'Yanggu-gun': '양구군',
    'Inje-gun': '인제군',
    'Goseong-gun': '고성군',
    'Yangyang-gun': '양양군',

    // Chungbuk
    'Cheongju-si': '청주시',
    'Chungju-si': '충주시',
    'Jecheon-si': '제천시',

    // Chungnam
    'Cheonan-si': '천안시',
    'Gongju-si': '공주시',
    'Boryeong-si': '보령시',
    'Asan-si': '아산시',
    'Seosan-si': '서산시',
    'Nonsan-si': '논산시',
    'Gyeryong-si': '계룡시',
    'Dangjin-si': '당진시',

    // Jeonbuk
    'Jeonju-si': '전주시',
    'Gunsan-si': '군산시',
    'Iksan-si': '익산시',
    'Jeongeup-si': '정읍시',
    'Namwon-si': '남원시',
    'Gimje-si': '김제시',

    // Jeonnam
    'Mokpo-si': '목포시',
    'Yeosu-si': '여수시',
    'Suncheon-si': '순천시',
    'Naju-si': '나주시',
    'Gwangyang-si': '광양시',

    // Gyeongbuk
    'Pohang-si': '포항시',
    'Gyeongju-si': '경주시',
    'Gimcheon-si': '김천시',
    'Andong-si': '안동시',
    'Gumi-si': '구미시',
    'Yeongju-si': '영주시',
    'Yeongcheon-si': '영천시',
    'Sangju-si': '상주시',
    'Mungyeong-si': '문경시',
    'Gyeongsan-si': '경산시',

    // Gyeongnam
    'Changwon-si': '창원시',
    'Jinju-si': '진주시',
    'Tongyeong-si': '통영시',
    'Sacheon-si': '사천시',
    'Gimhae-si': '김해시',
    'Miryang-si': '밀양시',
    'Geoje-si': '거제시',
    'Yangsan-si': '양산시',

    // Jeju
    'Jeju-si': '제주시',
    'Seogwipo-si': '서귀포시',
};

// Handle specific Suwon districts if they exist in geojson
Object.assign(DISTRICT_TRANSLATION, {
    'Suwon-si Jangangu': '장안구',
    'Suwon-si Gwonseongu': '권선구',
    'Suwon-si Paldalgu': '팔달구',
    'Suwon-si Yeongtonggu': '영통구',
    'Seongnam-si Sujeong-gu': '수정구',
    'Seongnam-si Jungwon-gu': '중원구',
    'Seongnam-si Bundang-gu': '분당구',
    'Anyang-si Manan-gu': '만안구',
    'Anyang-si Dongan-gu': '동안구',
    'Goyang-si Deogyang-gu': '덕양구',
    'Goyang-si Ilsandong-gu': '일산동구',
    'Goyang-si Ilsanseo-gu': '일산서구',
    'Yongin-si 처인구': 'Cheoin-gu', // Wait, map is English Key -> Korean Value
    'Yongin-si Cheoin-gu': '처인구',
    'Yongin-si Giheung-gu': '기흥구',
    'Yongin-si Suji-gu': '수지구',
    'Ansan-si Sangnok-gu': '상록구',
    'Ansan-si Danwon-gu': '단원구',
    'Cheongju-si Sangdang-gu': '상당구',
    'Cheongju-si Seowon-gu': '서원구',
    'Cheongju-si Heungdeok-gu': '흥덕구',
    'Cheongju-si Cheongwon-gu': '청원구',
    'Cheonan-si Dongnam-gu': '동남구',
    'Cheonan-si Seobuk-gu': '서북구',
    'Jeonju-si Wansan-gu': '완산구',
    'Jeonju-si Deokjin-gu': '덕진구',
    'Pohang-si Nam-gu': '남구',
    'Pohang-si Buk-gu': '북구',
    'Changwon-si Uichang-gu': '의창구',
    'Changwon-si Seongsan-gu': '성산구',
    'Changwon-si Masannapo-gu': '마산합포구',
    'Changwon-si Masanhoewon-gu': '마산회원구',
    'Changwon-si Jinhae-gu': '진해구',
});
